table:
  name: MeterValues
  schema: public
object_relationships:
  - name: StopTransaction
    using:
      foreign_key_constraint_on: stopTransactionDatabaseId
  - name: Tenant
    using:
      foreign_key_constraint_on: tenantId
  - name: Transaction
    using:
      foreign_key_constraint_on: transactionDatabaseId
  - name: TransactionEvent
    using:
      foreign_key_constraint_on: transactionEventId
