version: '3'
services:
  amqp-broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  ocpp-db:
    image: citrineos/postgres:preseeded
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: citrine
      POSTGRES_USER: citrine
      POSTGRES_PASSWORD: "citrine"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    environment:
      KEY: '1234567890'
      SECRET: '0987654321'
      ADMIN_EMAIL: 'admin@citrineos.com'
      ADMIN_PASSWORD: 'CitrineOS!'
      DB_CLIENT: 'pg'
      DB_HOST: ocpp-db
      DB_PORT: 5432
      DB_DATABASE: 'citrine'
      DB_USER: 'citrine'
      DB_PASSWORD: 'citrine'
      WEBSOCKETS_ENABLED: 'true'
  citrine:
    build:
      context: ../
      dockerfile: ./Swarm/docker/server/Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./:/usr/server
      - /usr/server/node_modules
  # certificates:
  #   build:
  #     context: ../
  #     dockerfile: ./Swarm/docker/module/Dockerfile
  #   depends_on:
  #     ocpp-db:
  #       condition: service_started
  #     amqp-broker:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./:/usr/certificates
  #     - /usr/certificates/node_modules
  #   environment:
  #     APP_NAME: 'Certificates'
  # configuration:
  #   build:
  #     context: ../
  #     dockerfile: ./Swarm/docker/module/Dockerfile
  #   depends_on:
  #     ocpp-db:
  #       condition: service_started
  #     amqp-broker:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./:/usr/configuration
  #     - /usr/configuration/node_modules
  #   environment:
  #     APP_NAME: 'Configuration'
  # evdriver:
  #   build:
  #     context: ../
  #     dockerfile: ./Swarm/docker/module/Dockerfile
  #   depends_on:
  #     ocpp-db:
  #       condition: service_started
  #     amqp-broker:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./:/usr/evdriver
  #     - /usr/evdriver/node_modules
  #   environment:
  #     APP_NAME: 'EVDriver'
  # monitoring:
  #   build:
  #     context: ../
  #     dockerfile: ./Swarm/docker/module/Dockerfile
  #   depends_on:
  #     ocpp-db:
  #       condition: service_started
  #     amqp-broker:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./:/usr/monitoring
  #     - /usr/monitoring/node_modules
  #   environment:
  #     APP_NAME: 'Monitoring'
  # reporting:
  #   build:
  #     context: ../
  #     dockerfile: ./Swarm/docker/module/Dockerfile
  #   depends_on:
  #     ocpp-db:
  #       condition: service_started
  #     amqp-broker:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./:/usr/reporting
  #     - /usr/reporting/node_modules
  #   environment:
  #     APP_NAME: 'Reporting'
  # smartcharging:
  #   build:
  #     context: ../
  #     dockerfile: ./Swarm/docker/module/Dockerfile
  #   depends_on:
  #     ocpp-db:
  #       condition: service_started
  #     amqp-broker:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./:/usr/smartcharging
  #     - /usr/smartcharging/node_modules
  #   environment:
  #     APP_NAME: 'SmartCharging'
  # transactions:
  #   build:
  #     context: ../
  #     dockerfile: ./Swarm/docker/module/Dockerfile
  #   depends_on:
  #     ocpp-db:
  #       condition: service_started
  #     amqp-broker:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./:/usr/transactions
  #     - /usr/transactions/node_modules
  #   environment:
  #     APP_NAME: 'Transactions'
