version: '3'
services:
  amqp-broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  ocpp-db:
    image: citrineos/postgres:preseeded
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: citrine
      POSTGRES_USER: citrine
      POSTGRES_PASSWORD: "citrine"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  citrine:
    build:
      context: ..
      dockerfile: ./Server/local.Dockerfile
    volumes:
      - ../:/usr/local/apps/citrineos
      - /usr/local/apps/citrineos/node_modules
      - /usr/local/apps/citrineos/Server/node_modules
      - /usr/local/apps/citrineos/00_Base/node_modules
      - /usr/local/apps/citrineos/01_Data/node_modules
      - /usr/local/apps/citrineos/02_Util/node_modules
      - /usr/local/apps/citrineos/03_Modules/Certificates/node_modules
      - /usr/local/apps/citrineos/03_Modules/Configuration/node_modules
      - /usr/local/apps/citrineos/03_Modules/EVDriver/node_modules
      - /usr/local/apps/citrineos/03_Modules/Monitoring/node_modules
      - /usr/local/apps/citrineos/03_Modules/OcppRouter/node_modules
      - /usr/local/apps/citrineos/03_Modules/Reporting/node_modules
      - /usr/local/apps/citrineos/03_Modules/SmartCharging/node_modules
      - /usr/local/apps/citrineos/03_Modules/Transactions/node_modules
      - /usr/local/apps/citrineos/dist/
      - /usr/local/apps/citrineos/Server/dist/
      - /usr/local/apps/citrineos/00_Base/dist/
      - /usr/local/apps/citrineos/01_Data/dist/
      - /usr/local/apps/citrineos/02_Util/dist/
      - /usr/local/apps/citrineos/03_Modules/Certificates/dist/
      - /usr/local/apps/citrineos/03_Modules/Configuration/dist/
      - /usr/local/apps/citrineos/03_Modules/EVDriver/dist/
      - /usr/local/apps/citrineos/03_Modules/Monitoring/dist/
      - /usr/local/apps/citrineos/03_Modules/OcppRouter/dist/
      - /usr/local/apps/citrineos/03_Modules/Reporting/dist/
      - /usr/local/apps/citrineos/03_Modules/SmartCharging/dist/
      - /usr/local/apps/citrineos/03_Modules/Transactions/dist/
    environment:
      APP_NAME: "all"
      APP_ENV: "docker"
      CITRINEOS_UTIL_DIRECTUS_USERNAME: 'admin@citrineos.com'
      CITRINEOS_UTIL_DIRECTUS_PASSWORD: 'CitrineOS!'
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 9229:9229

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    depends_on:
      ocpp-db:
        condition: service_healthy
    environment:
      APP_NAME: 'all'
      KEY: '1234567890'
      SECRET: '0987654321'
      ADMIN_EMAIL: 'admin@citrineos.com'
      ADMIN_PASSWORD: 'CitrineOS!'
      DB_CLIENT: 'pg'
      DB_HOST: ocpp-db
      DB_PORT: 5432
      DB_DATABASE: 'citrine'
      DB_USER: 'citrine'
      DB_PASSWORD: 'citrine'
      WEBSOCKETS_ENABLED: 'true'