name: Publish Swagger

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and Run Docker Compose
        run: | 
          docker compose -f ${{ github.workspace }}/Server/docker-compose.yml up -d

      - name: Download Swagger JSON
        run: |
          echo "Fetching Swagger JSON..."
          curl --retry 3 --retry-delay 3 --retry-all-errors -o swagger.json http://localhost:8080/docs/json 
          cat swagger.json

#      - name: Push Swagger JSON to citrineos.github.io
#        run: |
#          git clone https://github.com/citrineos/citrineos.github.io.git
#          cd citrineos.github.io
#          git checkout -b swagger-updates || git checkout swagger-updates
#          cp ../swagger.json .
#          git config user.name "GitHub Actions"
#          git config user.email "actions@github.com"
#          git add swagger.json
#          git commit -m "Update Swagger JSON from PR"
#          git push origin swagger-updates --verbose
#      - name: Push Swagger JSON to citrineos.github.io

      - name: Download Swagger JSON
        uses: actions/checkout@v4
        with:
          repository: citrineos/citrineos.github.io
          path: citrineos.github.io
      - run: |
          pwd
          ls
          ls ..

      - name: Clean up
        run: docker compose -f ${{ github.workspace }}/Server/docker-compose.yml down
