name: Publish Swagger

on:
  pull_request:

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and Run Docker Compose
        run: | 
          docker compose -f ${{ github.workspace }}/Server/docker-compose.yml up -d

      - name: Download Swagger JSON
        run: |
          echo "Fetching Swagger JSON..."
          curl --retry 3 --retry-delay 3 --retry-all-errors -o swagger.json http://localhost:8080/docs/json 
          cat swagger.json

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CITRINEOS_GITHUB_IO_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push Swagger JSON to citrineos.github.io
        run: |
          git clone git@github.com:citrineos/citrineos.github.io.git
          cd citrineos.github.io
          git checkout -b swagger-updates || git checkout swagger-updates
          cp ../swagger.json .
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add swagger.json
          git commit -m "Update Swagger JSON from PR"
          git push -f origin swagger-updates --verbose

      - name: Clean up
        run: docker compose -f ${{ github.workspace }}/Server/docker-compose.yml down
