name: Push Release Tagged Server

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  SERVER_IMAGE_NAME: citrineos-server
  DIRECTUS_IMAGE_NAME: citrineos-directus

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Server image
        run: docker build . --file ./Server/deploy.Dockerfile --tag SERVER_IMAGE_NAME

      - name: Build Directus image
        run: docker build . --file ./DirectusExtensions/directus.Dockerfile --tag $DIRECTUS_IMAGE_NAME
      - name: Copy config file to Directus container
        run: |
          container_id=$(docker create $DIRECTUS_IMAGE_NAME)
          docker cp ./Server/directus-env-config.cjs $container_id:/directus/config.cjs
          docker commit $container_id $DIRECTUS_IMAGE_NAME
          docker rm $container_id

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${SERVER_IMAGE_NAME}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $SERVER_IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $SERVER_IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

      - name: Push Directus image
        run: |
          DIRECTUS_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${DIRECTUS_IMAGE_NAME}
          DIRECTUS_IMAGE_ID=$(echo $DIRECTUS_IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo DIRECTUS_IMAGE_ID=$DIRECTUS_IMAGE_ID
          echo VERSION=$VERSION

          docker tag $DIRECTUS_IMAGE_NAME $DIRECTUS_IMAGE_ID:$VERSION
          docker tag $DIRECTUS_IMAGE_NAME $DIRECTUS_IMAGE_ID:latest
          docker push $DIRECTUS_IMAGE_ID:$VERSION
          docker push $DIRECTUS_IMAGE_ID:latest
