name: Build Server on Pull Request

on:
  pull_request:

env:
  IMAGE_NAME: citrineos-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        run: docker build ./Server --file Server/docker/Dockerfile --tag $IMAGE_NAME
