name: Test Server on Pull Request

on:
  push:
    branches:
      - feature/ci

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set permissions on the uploads directory
        run: |
          sudo chown 1000:1000 ${{ github.workspace }}/Server/data/directus/uploads
          sudo chmod 775 ${{ github.workspace }}/Server/data/directus/uploads

      - name: Build and Run Docker Compose
        run: docker-compose -f ${{ github.workspace }}/Server/docker-compose.yml up -d

      - name: Install Newman
        run: npm install -g newman

      - name: Integration test
        run: echo "Run tests"

      - name: Get logs for all containers
        if: failure()
        run: | 
          docker ps -a
          docker container ls -aq | xargs -I {} docker logs {}

      - name: Clean up
        run: docker-compose -f ${{ github.workspace }}/Server/docker-compose.yml down
